# Generated by Django 3.2.5 on 2021-08-17 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('floor_number', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], default='available', max_length=50)),
                ('number_of_tables', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/restaurants/main')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/restaurants/other')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/restaurants/other')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/restaurants/other')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
