# Generated by Django 3.2.5 on 2021-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210920_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_number_of_people',
            field=models.IntegerField(default=50),
        ),
    ]
