# Generated by Django 3.2.5 on 2021-09-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_max_number_of_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='max_number_of_people',
            new_name='max_number_of_people_for_reservation',
        ),
    ]
