# Generated by Django 3.2.5 on 2021-09-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_max_number_of_people_restaurant_max_number_of_people_for_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_number_of_people_for_reservation',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
