# Generated by Django 3.2.5 on 2021-08-13 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room_types.roomtype')),
            ],
        ),
    ]
