# Generated by Django 3.2.5 on 2021-08-28 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_items', '0002_menuitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number_of_items', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/special_offers/')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu_items.menuitem')),
            ],
        ),
    ]
