# Generated by Django 3.2.5 on 2021-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offers', '0002_alter_specialoffer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
