# Generated by Django 3.2.5 on 2021-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='reserved_date',
            field=models.DateField(blank=True),
        ),
    ]
