# Generated by Django 3.2.5 on 2021-08-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number_of_adults', models.IntegerField()),
                ('number_of_beds', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/roomTypes/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/roomTypes/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/roomTypes/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/roomTypes/')),
            ],
        ),
    ]
