# Generated by Django 3.2.5 on 2021-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
