# Generated by Django 3.2.5 on 2021-09-23 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_alter_restaurant_max_number_of_people_for_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('table_no', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Initialized', 'initialized'), ('Confirmed', 'confirmed'), ('In_Progress', 'in_progress'), ('Created', 'created'), ('Being_Delivered', 'being_delivered'), ('Delivered', 'delivered'), ('Paid', 'paid')], default='Initialized', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('menu_items', models.CharField(default='{}', max_length=255)),
                ('special_offers', models.CharField(default='{}', max_length=255)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.restaurant')),
            ],
        ),
    ]
