# Generated by Django 3.2.5 on 2021-09-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0003_alter_customerorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
