# Generated by Django 3.2.5 on 2021-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0004_alter_customerorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('created', 'Created'), ('being_delivered', 'Being_Delivered'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='initialized', max_length=50),
        ),
    ]
